### ISSUE TITLE
Optimize Android Extraction for handling large data dumps

### ISSUE THREAD

**Issue by mitshubh** [twinklegupta/CS230-Project#10]
Current android-extraction process waits for all the apk's to be successfully extracted (via apktool), before beginning to process the AndroidManifest.xml files for each application. This becomes a huge bottleneck for the system as the input application count count increase.

**Comment by mitshubh** [comment]
Committed code via Pull Request #12 .

**Comment by mitshubh** [comment]
Reopening - Adding capability to process android applications as and when they have been extracted (no particular order - reduces wait time)

**Comment by BrendonFaleiro** [comment]
While you r working on this, fix the part where you find the apkName. Its right now platform dependent (assumes filesystem is UNIX). Use either FilenameUtils or File.getName() instead.

**Comment by mitshubh** [comment]
@BrendonFaleiro Postponed.
