### ISSUE TITLE
Dataset Crawling 

### ISSUE THREAD

**Issue by mitshubh** [twinklegupta/CS230-Project#2]
Crawl and obtain android applications for third party Android Market Stores

**Comment by amehrotra91** [comment]
In Progress. Starting with the play store

**Comment by amehrotra91** [comment]
Apks from playstore committed to the repository.

**Comment by amehrotra91** [comment]
Closing this issue. Based on the final evaluation strategy will decide if we need apks from third party Android Market Stores like Anzhi.
