### ISSUE TITLE
Feature (Bit) Vector Creation

### ISSUE THREAD

**Issue by mitshubh** [twinklegupta/CS230-Project#3]
Window and Hash the opcode file such that each opcode list represents a single bit vector

**Comment by swati3124** [comment]
In Progress

Code for K-gram, djb2 Hashing and similarity on basis of Jaccard distance is done. 
Working on integrating it with opcode format and K-grams to feature vector creation.

**Comment by BrendonFaleiro** [comment]
https://github.com/chehsunliu/android-malware-detection/tree/master/tools/feature

You can take a look at this too for ideas on feature extraction

**Comment by swati3124** [comment]
Will do. Thank you

**Comment by swati3124** [comment]
This part is complete. Closing this issue.
