### ISSUE TITLE
Malware Intrusion

### ISSUE THREAD

**Issue by mitshubh** [twinklegupta/CS230-Project#5]
Inject malware to the apk and repackage.

**Comment by mitshubh** [comment]
Malware samples(apart from Contagio) that are available on the web:
https://github.com/ashishb/android-malware
https://github.com/cskamil/Android-Application-Dataset-for-Malware-Detection

**Comment by sodhanipranav** [comment]
This might be of some help. https://code.google.com/archive/p/androguard/wikis/DatabaseAndroidMalwares.wiki

**Comment by amehrotra91** [comment]
Thanks! will look into it

**Comment by BrendonFaleiro** [comment]
you can take a look at this too for malware 
https://github.com/gbrindisi/malware/tree/master/android/gmbot

**Comment by twinklegupta** [comment]
Sure will do.

**Comment by amehrotra91** [comment]
We can use this to learn how to repackage it with malware:
http://gauss.ececs.uc.edu/Courses/c653/homework/assgn6.pdf

**Comment by amehrotra91** [comment]
final dataset created by Twinkle and uploaded online
