### ISSUE TITLE
APK Extraction and Parsing

### ISSUE THREAD

**Issue by mitshubh** [twinklegupta/CS230-Project#6]
Extract the list of Apk's (Test different tools for apk decompiling) and create the Basic Block file to be fed for feature vector creation

**Comment by mitshubh** [comment]
The output is a serialized object of the curated opcode list. You'll have to deserialize it to process for the hashing process. The format is as follows:

.class <CLASS_NAME>
.method <METHOD_NAME>
opcode1
opcode2
...
.method <METHOD_NAME>
opcode1
opcode2
...
.class <CLASS_NAME>
...
 Delete branch

**Comment by twinklegupta** [comment]
Steps to extract opcode list using dedexer tool ( for mac )-
1. rename appname.apk to appname.zip
2. download dedexer jar named ddx.26.jar
3. run the command java -jar ddx.26.jar -d <output folder> <dex file>

**Comment by twinklegupta** [comment]
applications produce many .ddx files (one for each activity) using the above method. should we use all?

**Comment by mitshubh** [comment]
Pushed the code for efficient parsing. Closing the issue.
