### ISSUE TITLE
Finalize Evaluation Strategy

### ISSUE THREAD

**Issue by mitshubh** [twinklegupta/CS230-Project#7]
What should we compare our similarity measurement to? Is there an existing benchmark?

**Comment by amehrotra91** [comment]
Under consideration:
1) Check related work for evaluation strategies.
2) Repackage a subset of the apks with malware and check if our implementation detects these apks.    Strategy used by the authors in the paper for Juxtapp. Details missing.
3) Find if there is a tool which can help us measure the containment between the APKs. And then compare it with our results. 
4) Check if there is a way to manually verify the result for a few APKs.

**Comment by amehrotra91** [comment]
@twinklegupta  has dropped a mail to the authors, regarding the details for evaluation and if they could release the dataset for apks with the malware.

**Comment by amehrotra91** [comment]
This is done! File attached in the repository. 
Discussed with Professor Kim.
