### ISSUE TITLE
Clustering - Evaluation

### ISSUE THREAD

**Issue by sodhanipranav** [twinklegupta/CS230-Project#9]

**Comment by BrendonFaleiro** [comment]
Need to update the fields for Clusters and distinguish between Items, Nodes and Clusters

**Comment by BrendonFaleiro** [comment]
Need to distinguish between the fields Items, Clusters and Nodes in ClusterT.
Also, all apk leaves should have isRoot = true. So that if apks are not merged into clusters they can be detected as roots.

**Comment by amehrotra91** [comment]
Can we close this? Or it's pending?

**Comment by mitshubh** [comment]
Completed.
